services:
  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    image: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpressV:/var/www/html
    networks:
      - my_network
    restart: on-failure

  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    container_name: mariadb
    image: mariadb
    networks:
      - my_network
    volumes:
      - mariadbV:/var/lib/mysql
    restart: on-failure

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    container_name: wordpress
    image: wordpress
    depends_on:
      - mariadb
    restart: on-failure
    volumes: 
      - wordpressV:/var/www/html
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  wordpressV:
    driver_opts:
      type: none
      o: bind
      device: /home/azaghlou/data/wordpress
  mariadbV:
    driver_opts:
      type: none
      o: bind
      device: /home/azaghlou/data/mariadb